### ISSUE TITLE
Can't build due to trace-file.json not being found

### ISSUE THREAD

**Issue by p-himik** [babashka/tools-deps-native#19]
Trying to build v0.0.4 on Linux but getting:
```
script/gen-reflect-config.clj $(clojure -Spath):classes
----- Error --------------------------------------------------------------------
Type:     java.io.FileNotFoundException
Message:  trace-file.json (No such file or directory)
Location: /home/p-himik/soft/tools-deps-native/script/gen-reflect-config.clj:41:40

----- Context ------------------------------------------------------------------
37: ;;         "{:deps {org.clojure/clojure {:mvn/version \"1.10.3\"}}}"])
38: 
39: ;; (trace->config ".")
40: 
41: (def trace-json (cheshire/parse-string (slurp "trace-file.json") true))
                                           ^--- trace-file.json (No such file or directory)
42: 
43: ;; [Z = boolean
44: ;; [B = byte
45: ;; [S = short
46: ;; [I = int

----- Stack trace --------------------------------------------------------------
clojure.core/slurp         - <built-in>
user                       - /home/p-himik/soft/tools-deps-native/script/gen-reflect-config.clj:41:40
cheshire.core/parse-string - <built-in>
user                       - /home/p-himik/soft/tools-deps-native/script/gen-reflect-config.clj:41:17
```

Seems like the code that generates `trace-file.json` was commented out but the code that reads that file was not.

**Comment by borkdude** [comment]
I'll take a look, but I think you should be able to build without this step now. Just run `script/compile.clj`.

**Comment by p-himik** [comment]
Hmm, that doesn't work either:
```
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Component Native Image (org.graalvm.native-image) is already installed.
borkdude.tdn.main
Init at build time:
clojure,borkdude.tdn,bencode,cognitect
Compiling
"borkdude.tdn.main"
("/home/p-himik/soft/graalvm-ce-java11-20.1.0/bin/native-image" "-cp" "src:resources:/home/p-himik/.m2/repository/com/cognitect/transit-clj/1.0.324/transit-clj-1.0.324.jar:/home/p-himik/.m2/repository/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar:/home/p-himik/.m2/repository/nrepl/bencode/1.1.0/bencode-1.1.0.jar:/home/p-himik/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar:/home/p-himik/.m2/repository/org/clojure/tools.deps.alpha/0.12.1067/tools.deps.alpha-0.12.1067.jar:/home/p-himik/.m2/repository/org/slf4j/slf4j-jdk14/1.7.9/slf4j-jdk14-1.7.9.jar:/home/p-himik/.m2/repository/com/cognitect/transit-java/1.0.343/transit-java-1.0.343.jar:/home/p-himik/.m2/repository/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar:/home/p-himik/.m2/repository/org/clojure/core.specs.alpha/0.2.56/core.specs.alpha-0.2.56.jar:/home/p-himik/.m2/repository/org/clojure/spec.alpha/0.2.194/spec.alpha-0.2.194.jar:/home/p-himik/.m2/repository/com/cognitect/aws/api/0.8.524/api-0.8.524.jar:/home/p-himik/.m2/repository/com/cognitect/aws/endpoints/1.1.12.93/endpoints-1.1.12.93.jar:/home/p-himik/.m2/repository/com/cognitect/aws/s3/814.2.991.0/s3-814.2.991.0.jar:/home/p-himik/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-core/3.8.3/maven-core-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-resolver-provider/3.8.3/maven-resolver-provider-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/resolver/maven-resolver-api/1.6.3/maven-resolver-api-1.6.3.jar:/home/p-himik/.m2/repository/org/apache/maven/resolver/maven-resolver-connector-basic/1.6.3/maven-resolver-connector-basic-1.6.3.jar:/home/p-himik/.m2/repository/org/apache/maven/resolver/maven-resolver-impl/1.6.3/maven-resolver-impl-1.6.3.jar:/home/p-himik/.m2/repository/org/apache/maven/resolver/maven-resolver-spi/1.6.3/maven-resolver-spi-1.6.3.jar:/home/p-himik/.m2/repository/org/apache/maven/resolver/maven-resolver-transport-file/1.6.3/maven-resolver-transport-file-1.6.3.jar:/home/p-himik/.m2/repository/org/apache/maven/resolver/maven-resolver-transport-http/1.6.3/maven-resolver-transport-http-1.6.3.jar:/home/p-himik/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.6.3/maven-resolver-util-1.6.3.jar:/home/p-himik/.m2/repository/org/clojure/data.xml/0.2.0-alpha6/data.xml-0.2.0-alpha6.jar:/home/p-himik/.m2/repository/org/clojure/tools.cli/1.0.206/tools.cli-1.0.206.jar:/home/p-himik/.m2/repository/org/clojure/tools.gitlibs/2.3.167/tools.gitlibs-2.3.167.jar:/home/p-himik/.m2/repository/org/eclipse/jetty/jetty-client/9.4.44.v20210927/jetty-client-9.4.44.v20210927.jar:/home/p-himik/.m2/repository/org/eclipse/jetty/jetty-http/9.4.44.v20210927/jetty-http-9.4.44.v20210927.jar:/home/p-himik/.m2/repository/org/eclipse/jetty/jetty-util/9.4.44.v20210927/jetty-util-9.4.44.v20210927.jar:/home/p-himik/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7.jar:/home/p-himik/.m2/repository/org/msgpack/msgpack/0.6.12/msgpack-0.6.12.jar:/home/p-himik/.m2/repository/com/cognitect/http-client/0.1.106/http-client-0.1.106.jar:/home/p-himik/.m2/repository/org/clojure/core.async/1.3.622/core.async-1.3.622.jar:/home/p-himik/.m2/repository/org/clojure/data.json/1.0.0/data.json-1.0.0.jar:/home/p-himik/.m2/repository/org/clojure/tools.logging/1.1.0/tools.logging-1.1.0.jar:/home/p-himik/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2-no_aop.jar:/home/p-himik/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-artifact/3.8.3/maven-artifact-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-builder-support/3.8.3/maven-builder-support-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-model/3.8.3/maven-model-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-model-builder/3.8.3/maven-model-builder-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-plugin-api/3.8.3/maven-plugin-api-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-repository-metadata/3.8.3/maven-repository-metadata-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-settings/3.8.3/maven-settings-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/maven-settings-builder/3.8.3/maven-settings-builder-3.8.3.jar:/home/p-himik/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar:/home/p-himik/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.jar:/home/p-himik/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar:/home/p-himik/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.26/plexus-interpolation-1.26.jar:/home/p-himik/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.5/org.eclipse.sisu.inject-0.3.5.jar:/home/p-himik/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.5/org.eclipse.sisu.plexus-0.3.5.jar:/home/p-himik/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/p-himik/.m2/repository/org/apache/httpcomponents/httpclient/4.5.12/httpclient-4.5.12.jar:/home/p-himik/.m2/repository/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar:/home/p-himik/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.30/jcl-over-slf4j-1.7.30.jar:/home/p-himik/.m2/repository/org/clojure/data.codec/0.1.0/data.codec-0.1.0.jar:/home/p-himik/.m2/repository/org/eclipse/jetty/jetty-io/9.4.44.v20210927/jetty-io-9.4.44.v20210927.jar:/home/p-himik/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:/home/p-himik/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar:/home/p-himik/.m2/repository/org/clojure/tools.analyzer.jvm/1.2.0/tools.analyzer.jvm-1.2.0.jar:/home/p-himik/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/p-himik/.m2/repository/com/google/guava/guava/25.1-android/guava-25.1-android.jar:/home/p-himik/.m2/repository/org/codehaus/plexus/plexus-sec-dispatcher/2.0/plexus-sec-dispatcher-2.0.jar:/home/p-himik/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar:/home/p-himik/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar:/home/p-himik/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar:/home/p-himik/.m2/repository/org/clojure/core.memoize/1.0.236/core.memoize-1.0.236.jar:/home/p-himik/.m2/repository/org/clojure/tools.analyzer/1.1.0/tools.analyzer-1.1.0.jar:/home/p-himik/.m2/repository/org/clojure/tools.reader/1.3.2/tools.reader-1.3.2.jar:/home/p-himik/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar:/home/p-himik/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/p-himik/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/home/p-himik/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/home/p-himik/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar:/home/p-himik/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/home/p-himik/.m2/repository/org/codehaus/plexus/plexus-cipher/2.0/plexus-cipher-2.0.jar:/home/p-himik/.m2/repository/org/codehaus/plexus/plexus-utils/3.4.1/plexus-utils-3.4.1.jar:/home/p-himik/.m2/repository/org/clojure/core.cache/1.0.207/core.cache-1.0.207.jar:/home/p-himik/.m2/repository/org/clojure/data.priority-map/1.0.0/data.priority-map-1.0.0.jar:classes" "-J-Xmx5g" "-H:Name=tools-deps-native" "-H:+ReportExceptionStackTraces" "-H:ReflectionConfigurationFiles=reflect-config-cleaned.json,reflect-config-manual.json" "-H:ResourceConfigurationFiles=resources.json" "-H:+JNI" "-H:Log=registerResource:" "-H:EnableURLProtocols=http,https,jar" "--enable-all-security-services" "-J-Dclojure.spec.skip-macros=true" "-J-Dclojure.compiler.direct-linking=true" "--initialize-at-build-time=clojure,borkdude.tdn,bencode,cognitect,cognitect,aws,org.slf4j" "--report-unsupported-elements-at-runtime" "--verbose" "--no-fallback" "--no-server" "--allow-incomplete-classpath")
Build on Server(pid: 113873, port: 44211)
[@native-image-args.txt:113873]    classlist:     137.43 ms,  0.96 GB
Error: Main entry point class 'borkdude.tdn.main' not found.
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Error while executing task: 
```

Seems strange that it asks to set `-H:+ReportExceptionStackTraces` even though it's already there.

**Comment by borkdude** [comment]
I have pushed some changed. Can you try again?

Note: use `script/compile.clj`, not `script/compile`, that is a bash script which was old and is now removed to not cause further confusion.

**Comment by p-himik** [comment]
Yeah, running the `.clj` one. And still the same error.

The build log in `~/.native-image` has this line:
```
2021-11-28T14:28:27.910266Z: -task=com.oracle.svm.hosted.NativeImageGeneratorRunner -imagecp /home/p-himik/soft/graalvm-ce-java11-20.1.0/lib/svm/builder/llvm-wrapper-shadowed.jar:/home/p-himik/soft/graalvm-ce-java11-20.1.0/lib/svm/builder/javacpp-shadowed.jar:/home/p-himik/soft/graalvm-ce-java11-20.1.0/lib/svm/builder/svm-llvm.jar:/home/p-himik/soft/graalvm-ce-java11-20.1.0/lib/svm/builder/objectfile.jar:/home/p-himik/soft/graalvm-ce-java11-20.1.0/lib/svm/builder/llvm-platform-specific-shadowed.jar:/home/p-himik/soft/graalvm-ce-java11-20.1.0/lib/svm/builder/svm.jar:/home/p-himik/soft/graalvm-ce-java11-20.1.0/lib/svm/builder/pointsto.jar:/home/p-himik/soft/graalvm-ce-java11-20.1.0/lib/svm/library-support.jar:/home/p-himik/soft/tools-deps-native -H:Path=/home/p-himik/soft/tools-deps-native -H:CLibraryPath=/home/p-himik/soft/graalvm-ce-java11-20.1.0/lib/svm/clibraries/linux-amd64 -H:Class=borkdude.tdn.main -H:Name=@native-image-args.txt

```

A bit suspicious that the classpath ends with `/home/p-himik/soft/tools-deps-native` and not `/home/p-himik/soft/tools-deps-native/src`. But maybe it's completely unrelated - I have no idea what I'm doing, I'm just looking through the output of `strace`.

**Comment by borkdude** [comment]
@p-himik You're running a rather old GraalVM version. Try 21.3.0.

**Comment by p-himik** [comment]
Seems to work, thanks!
